{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "keycloak.fullname" . }}
    app.kubernetes.io/component: postgres
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keycloak.fullname" . }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keycloak.fullname" . }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}-secret
                  key: KC_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}-secret
                  key: KC_DB_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.keycloak.db.name | quote }}
            - name: POSTGRES_LOG_STATEMENT
              value: {{ .Values.db.logStatement | quote }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          {{- if .Values.db.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.db.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}