apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  labels:
    app: keycloak
data:
  deploy-realm.hurl: |
{{ (.Files.Get "deploy-keycloak-realm.hurl") | indent 4 }}

  realm-export.json: |
{{ (.Files.Get "realm-export.json") | indent 4 }}