apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
  # Ajoutez d'autres labels si besoin
  # namespace: {{ .Values.ingress.namespace }} # décommentez si vous souhaitez le namespace
  # type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.admin.username | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | quote }}
  KC_DB_USERNAME: {{ .Values.keycloak.db.username | quote }}
  KC_DB_PASSWORD: {{ .Values.keycloak.db.password | quote }}