apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
data:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.admin.username | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | b64enc | quote }}
  KC_DB_USERNAME: {{ .Values.keycloak.db.username | b64enc | quote }}
  KC_DB_PASSWORD: {{ .Values.keycloak.db.password | b64enc | quote  }}