keycloak:
  image: quay.io/keycloak/keycloak
  imageTag: 26.2.5
  replicaCount: 2
  resources:
    limits:
      cpu: 2000m
      memory: 2000Mi
    requests:
      cpu: 500m
      memory: 1700Mi
  host: ''
  tlsEnabled: false
  admin:
    username: ''
    password: ''
  db:
    username: ''
    password: ''
    database: postgres
    host: postgres

postgres:
  image: mirror.gcr.io/postgres:17
  db: keycloak
  host: postgres


ingress:
  name: keycloak-ingress
  namespace: ''
  class: alb
  annotations:
    acmCertificateArn: ''
    listenPorts: '[{"HTTP":80}]'
    sslRedirect: "443"
    loadBalancerAttributes: 'routing.http.drop_invalid_header_fields.enabled=true'
    scheme: internal
    targetType: ip
    backendProtocol: HTTP
    healthcheckPort: "status-port"
    healthcheckProtocol: HTTP
    subnetAllowList: ''
  tlsEnabled: false
  tlsSecretName: keycloak-tls
  host: ''
  path: "/"
  pathType: Prefix
  serviceName: keycloak
  servicePort: 8080
  servicePortName: keycloak
  extraPaths:
    - path: /health/*
      pathType: Prefix
    - path: /health
      pathType: Prefix
    - path: /metrics
      pathType: Prefix

# Les credentials sont gérés via des secrets Kubernetes (keycloak-admin et keycloak-db)
# Pour les tests, créez les secrets avec :
# kubectl create secret generic keycloak-admin --from-literal=username=admin --from-literal=password=admin
# kubectl create secret generic keycloak-db --from-literal=username=keycloak --from-literal=password=keycloak
