keycloak:
  image: quay.io/keycloak/keycloak:26.2.4
  replicaCount: 2
  resources:
    limits:
      cpu: 2000m
      memory: 2000Mi
    requests:
      cpu: 500m
      memory: 1700Mi
  host: keyclaok-preprod.asea.cqen.ca
  tlsEnabled: false

postgres:
  image: mirror.gcr.io/postgres:17
  db: keycloak
  host: postgres

ingress:
  name: keycloak-ingress
  namespace: keycloak-test
  class: alb
  annotations:
    certificateArn: ''
    listenPorts: '[{"HTTPS":443}]'
    sslRedirect: "443"
    loadBalancerAttributes: 'routing.http.drop_invalid_header_fields.enabled=true'
    scheme: internal
    targetType: ip
    backendProtocol: HTTPS
    healthcheckPort: "status-port"
    healthcheckProtocol: HTTP
    subnets: ''
  tlsEnabled: false
  tlsSecretName: keycloak-tls
  host: keyclaok-preprod.asea.cqen.ca
  path: "/"
  pathType: Prefix
  serviceName: keycloak
  servicePortName: https
  servicePort: 443

# Les credentials sont gérés via des secrets Kubernetes (keycloak-admin et keycloak-db)
# Pour les tests, créez les secrets avec :
# kubectl create secret generic keycloak-admin --from-literal=username=admin --from-literal=password=admin
# kubectl create secret generic keycloak-db --from-literal=username=keycloak --from-literal=password=keycloak
