name: Pull Request Validation Terraform Dev

on:
  pull_request:
    branches:
      - 'main'

env:
  AWS_REGION: "ca-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      argocd-changes: ${{ steps.check-argocd-changes.outputs.changes }}

    steps:
      - name: Checkout source and target branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to access both branches
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch target branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Check changes in argocd directory
        id: check-argocd-changes
        run: |
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -q "argocd/apps/"; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

  Validation-Terraform-and-plan-argocd:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.argocd-changes == 'true' }}
    uses: ./.github/workflows/plan-apps.yml
    secrets: inherit
    with:
      environment: preprod