name: Pull Request Validation Terraform Dev

on:
  push:
    branches:
      - 'main'

env:
  AWS_REGION: "ca-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      argocd-changes: ${{ steps.check-argocd-changes.outputs.changes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          git fetch --prune --unshallow --tags --all || git fetch --all
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "changed_files<<EOF" >> $GITHUB_ENV
          echo "$changed_files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check changes in argocd directory
        id: check-argocd-changes
        run: |
          if echo "$changed_files" | grep -q "argocd/apps/"; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

  Terraform-and-apply-argocd:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.argocd-changes == 'true' }}
    uses: ./.github/workflows/apply-apps.yml
    secrets: inherit
    with:
      environment: preprod