name: Validation du Realm Keycloak

on:
  workflow_dispatch:
  pull_request:        # Déclenchement sur pull request
    branches:
      - main

jobs:
  test-realm-configuration:
    name: Tests d'API Admin Keycloak
    runs-on: ubuntu-latest
    environment: test

    env:
      KEYCLOAK_URL: ${{ secrets.KEYCLOAK_URL_TEST }}
      KC_ADMIN_USER: ${{ secrets.KEYCLOAK_ADMIN_USERNAME_TEST }}
      KC_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD_TEST }}
      KEYCLOAK_API_CLIENT_SECRET: ${{secrets.KEYCLOAK_API_CLIENT_SECRET}}
      TARGET_REALM: 'mon-realm-deploiement' 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Installer les dépendances de test
        run: |
          pip install --upgrade pip
          # Installation du framework de test et de la librairie HTTP
          pip install pytest requests

      - name: Déploiement du Realm test
        uses: MCN-CQEN/ceai-cqen-scripts-lib/actions/keycloak-actions/deploy-realm@feature/deployer_realms  # Chemin vers votre action
        with:
          # Fichier de configuration spécifique à Staging
          realm-file: realms/septembre.json
          # URL spécifique à l'environnement de test
          keycloak_url: ${{ secrets.KEYCLOAK_URL }}
          keycloak_username: ${{ env.KC_ADMIN_USER }}
          keycloak_password: ${{ env.KC_ADMIN_PASSWORD }}

      - name: Exécuter les tests du Realm Keycloak
        run: pytest test-api/
        working-directory: .